// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpxWbKMkLhd6OayK4CDCTzNK1y6wbau0g',
    appId: '1:293611537856:web:1396724c55e062f9e5b425',
    messagingSenderId: '293611537856',
    projectId: 'vineyard-guard',
    authDomain: 'vineyard-guard.firebaseapp.com',
    databaseURL: 'https://vineyard-guard-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vineyard-guard.appspot.com',
    measurementId: 'G-2MXLQCKH4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK50Jo5l14bAaEPUk60opEtysMiQEmXJA',
    appId: '1:293611537856:android:1c6a21f6e32a8fd6e5b425',
    messagingSenderId: '293611537856',
    projectId: 'vineyard-guard',
    databaseURL: 'https://vineyard-guard-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vineyard-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwXnK9TBtiB1NkMBlou3xFJSN4hNNUdww',
    appId: '1:293611537856:ios:1e9925b2a03f9460e5b425',
    messagingSenderId: '293611537856',
    projectId: 'vineyard-guard',
    databaseURL: 'https://vineyard-guard-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vineyard-guard.appspot.com',
    iosBundleId: 'com.example.vineyardGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwXnK9TBtiB1NkMBlou3xFJSN4hNNUdww',
    appId: '1:293611537856:ios:1e9925b2a03f9460e5b425',
    messagingSenderId: '293611537856',
    projectId: 'vineyard-guard',
    databaseURL: 'https://vineyard-guard-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vineyard-guard.appspot.com',
    iosBundleId: 'com.example.vineyardGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpxWbKMkLhd6OayK4CDCTzNK1y6wbau0g',
    appId: '1:293611537856:web:66a708569f2a067ae5b425',
    messagingSenderId: '293611537856',
    projectId: 'vineyard-guard',
    authDomain: 'vineyard-guard.firebaseapp.com',
    databaseURL: 'https://vineyard-guard-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vineyard-guard.appspot.com',
    measurementId: 'G-CMT87HM58N',
  );
}
